#!/usr/bin/env php
<?php
//THIS IS NOT LARAVEL ARTISAN. THIS IS LUMI ARTISAN.
//TYPE php artisan help TO SEE AVAILABLE COMMANDS

function loadEnv() {
    if ( !file_exists('.env.local') ) {
        echo "\033[31mError:\033[0m .env.local file is missing.";
        return;
    }

    $lines = file('.env.local', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    foreach ($lines as $line) {
        if (strpos(trim($line), '#') === 0) {
            continue;
        }

        list($name, $value) = explode('=', $line, 2);
        $name = trim($name);
        $value = trim($value);

        if (!array_key_exists($name, $_SERVER) && !array_key_exists($name, $_ENV)) {
            putenv(sprintf('%s=%s', $name, $value));
            $_ENV[$name] = $value;
        }
    }
}

loadEnv();
require __DIR__.'/vendor/autoload.php';
\Lumi\Vue\Artisan\Artisan::run($argv);
